### ISSUE TITLE
About Metro Manila

### ISSUE THREAD

**Issue by skyyen999** [5SMNOONMS5/buy#1]
hello, 有兩千萬人口的應該是馬尼拉大都會(Metro Manila)加上周圍的省分(province)，只算馬尼拉大都會人口大約是1300萬人。馬尼拉大都會類似東京都的概念，由17個城市組成，其中人口最多的是有接近300萬人口的奎松市(QC)，第二的是馬尼拉市(Manila City)，接近200萬人。

以上資訊來源 https://en.wikipedia.org/wiki/Metro_Manila

**Comment by 5SMNOONMS5** [comment]
謝拉 哈哈
